SmallGameLibrary: sgl::Widgets::Layout Class Reference
sgl::Widgets::Layout Class Reference
A collection of widgets working together, graphically united.
#include <Layout.hpp>
Public Member Functions
Layout (int id, Base::Ptr parent, const sf::IntRect &bounds)
Construct a new Layout object.
virtual ~Layout ()
Destroy the Layout object.
virtual void onUpdate (const sf::Time dt)
Update the layout and its children.
virtual void onEvent (const sf::Event &event)
Called when an event is received, dispatching the event to all the children corresponding to the event type.
template<typename W , typename... Args>
W * add (Args &&... args)
Create a new widget in place and add it to the layout.
void onRender (sf::RenderTarget &screen, const sf::Transform &transform)
Render the widget on screen.
Public Member Functions inherited from sgl::Widgets::Base
Base (int id, Ptr parent, const sf::IntRect &bounds)
Construct a new Base widget object.
virtual ~Base ()
Destroy the Base widget object.
virtual void onTextEntered (sf::Uint32 code)
Called when a text entered event is produced, on focus.
virtual void onKeyPressed (int key)
Called when a key is pressed, on focus.
virtual void onKeyReleased (int key)
Called when a key is released, on focus.
virtual void onMouseWheelScrolled (float delta)
Called when the mouse wheel is scrolled, on focus.
virtual void onMouseButtonPressed (int button, int x, int y)
Called when a mouse button is pressed, on focus.
virtual void onMouseButtonReleased (int button, int x, int y)
Called when a mouse button is released, on focus.
virtual sf::FloatRect getLocalBounds () final
Get the local bounding rectangle of the entity.
virtual sf::FloatRect getGlobalBounds () final
Get the global bounding rectangle of the entity.
virtual void setListenToEvents (bool value) final
Activate a widget event listener or not.
virtual bool isListeningToEvents () const final
Return a boolean telling if the widget is listening to events.
virtual bool hasFocus () const final
Tell if the widget is being focused or not.
virtual void setStyle (Style style) final
Set the style of the object.
virtual Style getStyle () const final
Get the style of the widget.
template<typename T >
T * as ()
Return the widget as another type (should be a widget subclass)
Public Member Functions inherited from sgl::Graphics::Node
Node ()
Construct a new Node object.
virtual ~Node ()
Destroy the Node object.
Node & move (float x, float y)
Combine the current transform with a translation.
Node & move (const sf::Vector2f &offset)
Combine the current transform with a translation.
Node & rotate (float angle)
Combine the current transform with a rotation.
Node & rotate (float angle, float centerX, float centerY)
Combine the current transform with a rotation.
Node & rotate (float angle, const sf::Vector2f &center)
Combine the current transform with a rotation.
Node & scale (float scaleX, float scaleY)
Combine the current transform with a scaling.
Node & scale (const sf::Vector2f &factors)
Combine the current transform with a scaling.
Node & scale (float scaleX, float scaleY, float centerX, float centerY)
Combine the current transform with a scaling.
Node & scale (const sf::Vector2f &factors, const sf::Vector2f &center)
Combine the current transform with a scaling.
sf::Transform & getTransform ()
Get the Transform object.
template<typename N , typename... Args>
N * attach (Args &&... args)
Attach a child node to this node.
virtual void render (sf::RenderTarget &target, const sf::Transform &parent) final
Render a node using the parent transform, then its children.
Additional Inherited Members
Public Types inherited from sgl::Widgets::Base
using Ptr = Base *
Protected Attributes inherited from sgl::Widgets::Base
const int m_id
Unique identifier for the widget.
bool m_focused
Tell if the widget is being focused or not.
bool m_listening
Tell if a widget can receive events.
sf::IntRect m_rect
Rectangle in which the widget is.
Ptr m_parent
Pointer to the parent widget.
Style m_style
Protected Attributes inherited from sgl::Graphics::Node
std::vector< std::shared_ptr< Node > > m_children
Detailed Description
A collection of widgets working together, graphically united.
Definition at line 23 of file Layout.hpp.
Constructor & Destructor Documentation
Layout()
sgl::Widgets::Layout::Layout (int id, Base::Ptr parent, const sf::IntRect & bounds)
Construct a new Layout object.
Parameters
id Unique identifier for the widget (automatically set)
parent Pointer to parent layout (automatically set)
bounds Local bounds of the layout
Definition at line 7 of file Layout.cpp.
~Layout()
sgl::Widgets::Layout::~Layout () virtual
Destroy the Layout object.
Definition at line 11 of file Layout.cpp.
Member Function Documentation
add()
template<typename W , typename... Args> W * sgl::Widgets::Layout::add (Args &&... args) inline
Create a new widget in place and add it to the layout.
Template Parameters
W Class name of the widget to add
param args Args arguments (other than the identifier and the parent's pointer)
Returns
W* Raw owned pointer to the widget
Definition at line 64 of file Layout.hpp.
References sgl::Graphics::Node::m_children.
onEvent()
void sgl::Widgets::Layout::onEvent (const sf::Event & event) virtual
Called when an event is received, dispatching the event to all the children corresponding to the event type.
Parameters
event
Reimplemented from sgl::Widgets::Base.
Definition at line 20 of file Layout.cpp.
References sgl::Widgets::Base::hasFocus(), sgl::Widgets::Base::isListeningToEvents(), sgl::Graphics::Node::m_children, sgl::Widgets::Base::m_focused, and sgl::Widgets::Base::onEvent().
onRender()
void sgl::Widgets::Layout::onRender (sf::RenderTarget & screen, const sf::Transform & transform) virtual
Render the widget on screen.
This function will be empty because all the nodes are automatically rendered by the base class sgl::Graphics::Node, and because a layout has nothing to show.
Parameters
screen
transform Given by parent automatically
Reimplemented from sgl::Widgets::Base.
Definition at line 36 of file Layout.cpp.
onUpdate()
void sgl::Widgets::Layout::onUpdate (const sf::Time dt) virtual
Update the layout and its children.
Parameters
dt Delta of time since last update
Reimplemented from sgl::Widgets::Base.
Definition at line 14 of file Layout.cpp.
References sgl::Graphics::Node::m_children, and onUpdate().
Referenced by onUpdate().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/include/Small/Widgets/Layout.hpp
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/source/Widgets/Layout.cpp