SmallGameLibrary: sgl::SharedLibrary Class Reference
sgl::SharedLibrary Class Reference
Class to load / unload shared library on Windows, Linux, MacOS and Android.
#include <SharedLibrary.hpp>
Public Member Functions
SharedLibrary ()
Construct a new empty Shared Library object.
SharedLibrary (const std::string &path)
Construct a new Shared Library object by loading a shared library from it's relative path.
~SharedLibrary ()
Destroy the Shared Library object.
void load (const std::string &path)
Load a shared library from its path.
void unload ()
Unload the shared library.
template<typename T >
T get (const std::string &procname)
Retrieve a function from the shared library, given it's type T and its name.
Private Attributes
std::string m_path
bool m_loaded
Detailed Description
Class to load / unload shared library on Windows, Linux, MacOS and Android.
Definition at line 35 of file SharedLibrary.hpp.
Constructor & Destructor Documentation
SharedLibrary() [1/2]
sgl::SharedLibrary::SharedLibrary ()
Construct a new empty Shared Library object.
Definition at line 9 of file SharedLibrary.cpp.
SharedLibrary() [2/2]
sgl::SharedLibrary::SharedLibrary (const std::string & path)
Construct a new Shared Library object by loading a shared library from it's relative path.
On Linux, loading a shared libray can fail if it isn't in the PATH, thus you need to prefix the path with './' to tell it to search in the current folder.
Parameters
path
Definition at line 13 of file SharedLibrary.cpp.
References load(), and m_path.
~SharedLibrary()
sgl::SharedLibrary::~SharedLibrary ()
Destroy the Shared Library object.
Definition at line 19 of file SharedLibrary.cpp.
References unload().
Member Function Documentation
get()
template<typename T > T sgl::SharedLibrary::get (const std::string & procname) inline
Retrieve a function from the shared library, given it's type T and its name.
Template Parameters
T The type of the function, eg void (*) (int) for a function returning nothing and taking an integer as argument
Parameters
procname The name of the function, case sensitive
Returns
T A pointer to the retrieved function
Definition at line 82 of file SharedLibrary.hpp.
load()
void sgl::SharedLibrary::load (const std::string & path)
Load a shared library from its path.
On Linux, loading a shared libray can fail if it isn't in the PATH, thus you need to prefix the path with './' to tell it to search in the current folder.
Parameters
path
Definition at line 24 of file SharedLibrary.cpp.
References m_loaded, m_path, and unload().
Referenced by SharedLibrary().
unload()
void sgl::SharedLibrary::unload ()
Unload the shared library.
Definition at line 46 of file SharedLibrary.cpp.
References m_loaded.
Referenced by load(), and ~SharedLibrary().
Member Data Documentation
m_loaded
bool sgl::SharedLibrary::m_loaded private
Definition at line 109 of file SharedLibrary.hpp.
Referenced by load(), and unload().
m_path
std::string sgl::SharedLibrary::m_path private
Definition at line 108 of file SharedLibrary.hpp.
Referenced by load(), and SharedLibrary().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/include/Small/System/SharedLibrary.hpp
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/source/System/SharedLibrary.cpp