SmallGameLibrary: sgl::Scenes::ArkScene Class Reference
sgl::Scenes::ArkScene Class Reference
Define a scene scriptable through ArkScript.
#include <ArkScene.hpp>
Public Member Functions
ArkScene (int id, const std::string &scriptName)
Construct a new Ark Scene object.
~ArkScene ()
Destroy the Ark Scene object.
void init (const Scripting::Config &config)
Initialize scripting data.
void onEvent (const sf::Event &event)
Event handling method.
void onUpdate (const sf::Time dt)
Scene updating method, called after having handled the events.
void onRender (sf::RenderTarget &screen)
Rendering method, called after having updated the scene.
void onQuit ()
Method called when the application is closing.
Public Member Functions inherited from sgl::Scene
Scene (int id)
Construct a new Scene object.
virtual ~Scene ()
Destroy the Scene object.
virtual void onRender (sf::RenderTarget &screen, const sf::Transform &transform)
Rendering method, called after having updated the scene.
virtual void onChange (void *data)
Method called when the scene manager changes the current scene.
virtual void setState (State state) final
Set the State object.
virtual const int getId () const final
Get the Id of the scene.
virtual const State getState () const final
Get the State of the scene.
Public Member Functions inherited from sgl::Graphics::Node
Node ()
Construct a new Node object.
virtual ~Node ()
Destroy the Node object.
Node & move (float x, float y)
Combine the current transform with a translation.
Node & move (const sf::Vector2f &offset)
Combine the current transform with a translation.
Node & rotate (float angle)
Combine the current transform with a rotation.
Node & rotate (float angle, float centerX, float centerY)
Combine the current transform with a rotation.
Node & rotate (float angle, const sf::Vector2f &center)
Combine the current transform with a rotation.
Node & scale (float scaleX, float scaleY)
Combine the current transform with a scaling.
Node & scale (const sf::Vector2f &factors)
Combine the current transform with a scaling.
Node & scale (float scaleX, float scaleY, float centerX, float centerY)
Combine the current transform with a scaling.
Node & scale (const sf::Vector2f &factors, const sf::Vector2f &center)
Combine the current transform with a scaling.
sf::Transform & getTransform ()
Get the Transform object.
template<typename N , typename... Args>
N * attach (Args &&... args)
Attach a child node to this node.
virtual void render (sf::RenderTarget &target, const sf::Transform &parent) final
Render a node using the parent transform, then its children.
Protected Attributes
std::string m_scriptName
Ark::State m_state
Ark::VM m_vm
Protected Attributes inherited from sgl::Scene
State m_state
The state of the scene (running, idle, stopped)
const int m_id
The unique identifier of the scene.
SceneManager * m_sceneManager
The SceneManager to be able to change active scene.
RessourceManager m_ressources
Ressource handler for the scene.
Protected Attributes inherited from sgl::Graphics::Node
std::vector< std::shared_ptr< Node > > m_children
Detailed Description
Define a scene scriptable through ArkScript.
Each scene is given a script with different functions to work correctly:
(let onLoad   (fun () {  loading code  }))
(let onEvent  (fun (event) {  event handling code  }))
(let onUpdate (fun (dt) {  update handling code  }))
(let onRender (fun (screen) {  rendering code  }))
(let onQuit   (fun () {  unloading code  }))
Definition at line 36 of file ArkScene.hpp.
Constructor & Destructor Documentation
ArkScene()
sgl::Scenes::ArkScene::ArkScene (int id, const std::string & scriptName)
Construct a new Ark Scene object.
Parameters
id The identifier of the scene
scriptName Filename of the ArkScript file for this scene
Definition at line 8 of file ArkScene.cpp.
~ArkScene()
sgl::Scenes::ArkScene::~ArkScene ()
Destroy the Ark Scene object.
Definition at line 13 of file ArkScene.cpp.
Member Function Documentation
init()
void sgl::Scenes::ArkScene::init (const Scripting::Config & config) virtual
Initialize scripting data.
Parameters
config
Reimplemented from sgl::Scene.
Definition at line 16 of file ArkScene.cpp.
References sgl::Scripting::Config::arkscriptLibDir, sgl::Scripting::bindGraphics(), sgl::Scripting::bindScenes(), sgl::Scripting::bindSystem(), sgl::Scripting::bindWidgets(), sgl::Scripting::Config::compiledScriptsDir, m_scriptName, m_state, and m_vm.
onEvent()
void sgl::Scenes::ArkScene::onEvent (const sf::Event & event) virtual
Event handling method.
Parameters
event
Reimplemented from sgl::Scene.
Definition at line 32 of file ArkScene.cpp.
References m_vm, and sgl::Scripting::sfEventToArk().
onQuit()
void sgl::Scenes::ArkScene::onQuit () virtual
Method called when the application is closing.
Reimplemented from sgl::Scene.
Definition at line 48 of file ArkScene.cpp.
References m_vm.
onRender()
void sgl::Scenes::ArkScene::onRender (sf::RenderTarget & screen)
Rendering method, called after having updated the scene.
Parameters
screen
Definition at line 42 of file ArkScene.cpp.
References m_vm.
onUpdate()
void sgl::Scenes::ArkScene::onUpdate (const sf::Time dt) virtual
Scene updating method, called after having handled the events.
Parameters
dt
Reimplemented from sgl::Scene.
Definition at line 37 of file ArkScene.cpp.
References m_vm, and sgl::Scripting::sfTimeToArk().
Member Data Documentation
m_scriptName
std::string sgl::Scenes::ArkScene::m_scriptName protected
Definition at line 88 of file ArkScene.hpp.
Referenced by init().
m_state
Ark::State sgl::Scenes::ArkScene::m_state protected
Definition at line 89 of file ArkScene.hpp.
Referenced by init().
m_vm
Ark::VM sgl::Scenes::ArkScene::m_vm protected
Definition at line 90 of file ArkScene.hpp.
Referenced by init(), onEvent(), onQuit(), onRender(), and onUpdate().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/include/Small/Scenes/ArkScene.hpp
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/source/Scenes/ArkScene.cpp