SmallGameLibrary: sgl::Application Class Reference
sgl::Application Class Reference
The main component of the library, handling the scenes and running the app.
#include <Application.hpp>
Public Member Functions
Application (const Settings &settings)
Construct a new Application object.
Application & setTitle (const std::string &title)
Set the Title of the SFML window.
Application & setVSync (bool state)
Set the Virtual Synchronization ON or OFF.
Application & setFPSLimit (int value)
Set the FPS limit.
Application & setDebug (bool state)
Set the Debug mode.
template<typename S >
Application & setCurrentScene ()
Set the Current Scene.
Application & setCurrentSceneId (int id)
Set the Current Scene Id object.
Application & setScripting (bool value)
Enable or disable scripting.
Application & configureScriptingEngine (const Scripting::Config &config)
Configure the scripting engine (doesn't turn on the scripting)
template<typename S , typename... Args>
Application & add (Args &&... args)
Add a scene to the application.
void run ()
Run the application until an error occurs or until the quit condition is met.
Private Member Functions
void onEvents ()
Handling basic events (closing window, triggering debug mode), and passing the events to the active scene.
void onUpdate (const sf::Time dt)
Update the current scene by giving it the time passed since the last update.
void onRender ()
Rendering debug interface if requested, as well as the current scene.
Private Attributes
Settings::Keys m_keys
sf::RenderWindow m_screen
sf::Transform m_transformBase
sf::Clock m_clock
SceneManager m_sceneManager
bool m_scriptingEnabled
Scripting::Config m_scriptingConfig
Ark::State m_state
Ark::VM m_vm
internal::Profiler m_profiler
bool m_showDebug
bool m_wireframe = false
bool m_vsync = false
Detailed Description
The main component of the library, handling the scenes and running the app.
Debug mode is showing an imgui debug interface, with a profiler to know what took time to execute. When scripting is turned on, it's expecting to find a main script named "main.ark" defining those functions:
(let onLoad (fun () {
     # code executed during loading
}))
(let onQuit (fun () {
     # code executed when closing
}))
Definition at line 87 of file Application.hpp.
Constructor & Destructor Documentation
Application()
sgl::Application::Application (const Settings & settings)
Construct a new Application object.
Debug mode is OFF by default, as well as the scripting engine
Parameters
settings The settings for the application (size of the window, style, additional settings for the underlying opengl context)
Definition at line 13 of file Application.cpp.
References sgl::Settings::height, m_screen, and sgl::Settings::width.
Member Function Documentation
add()
template<typename S , typename... Args> Application & sgl::Application::add (Args &&... args) inline
Add a scene to the application.
Create the scene in place.
Template Parameters
S The type of the scene
Args
Parameters
args Arguments for the constructor of the scene
Returns
Application&
Definition at line 183 of file Application.hpp.
References sgl::SceneManager::add(), and m_sceneManager.
configureScriptingEngine()
Application & sgl::Application::configureScriptingEngine (const Scripting::Config & config)
Configure the scripting engine (doesn't turn on the scripting)
Compile all the scripts automatically, and give them to the VM to register them. Bind the small game library in ArkScript.
Parameters
config
Returns
Application&
Definition at line 80 of file Application.cpp.
References sgl::Scripting::Config::arkscriptLibDir, sgl::Scripting::bindCore(), sgl::Scripting::bindGraphics(), sgl::Scripting::bindScenes(), sgl::Scripting::bindSystem(), sgl::Scripting::bindWidgets(), sgl::Scripting::compileAllScriptsIn(), sgl::Scripting::Config::compiledScriptsDir, m_scriptingConfig, m_state, m_vm, and sgl::Scripting::Config::scriptsDirectory.
onEvents()
void sgl::Application::onEvents () inline private
Handling basic events (closing window, triggering debug mode), and passing the events to the active scene.
Referenced by run().
onRender()
void sgl::Application::onRender () inline private
Rendering debug interface if requested, as well as the current scene.
Referenced by run().
onUpdate()
void sgl::Application::onUpdate (const sf::Time dt) inline private
Update the current scene by giving it the time passed since the last update.
Parameters
dt
Referenced by run().
run()
void sgl::Application::run ()
Run the application until an error occurs or until the quit condition is met.
The builtin quit condition is when the click on the close button, this will call the method onQuit of each scene.
Definition at line 115 of file Application.cpp.
References sgl::internal::Profiler::Frame(), sgl::SceneManager::init(), m_clock, m_profiler, m_sceneManager, m_screen, m_scriptingConfig, m_scriptingEnabled, m_vm, onEvents(), onRender(), and onUpdate().
setCurrentScene()
template<typename S > Application & sgl::Application::setCurrentScene () inline
Set the Current Scene.
By default, no scene is selected, thus nothing will be rendered
Template Parameters
S The type of the scene
Returns
Application&
Definition at line 140 of file Application.hpp.
References m_sceneManager, and sgl::SceneManager::setCurrent().
setCurrentSceneId()
Application & sgl::Application::setCurrentSceneId (int id)
Set the Current Scene Id object.
Parameters
id the id of the scene
Returns
Application&
Definition at line 66 of file Application.cpp.
References m_sceneManager, and sgl::SceneManager::setCurrentId().
setDebug()
Application & sgl::Application::setDebug (bool state)
Set the Debug mode.
If the Debug mode is ON, ImGui tools will be displayed
Parameters
state
Returns
Application&
Definition at line 60 of file Application.cpp.
References m_showDebug.
setFPSLimit()
Application & sgl::Application::setFPSLimit (int value)
Set the FPS limit.
Parameters
value
Returns
Application&
Definition at line 53 of file Application.cpp.
References m_screen.
setScripting()
Application & sgl::Application::setScripting (bool value)
Enable or disable scripting.
By default, scripting is turned off
Parameters
value
Returns
Application&
Definition at line 73 of file Application.cpp.
References m_scriptingEnabled.
setTitle()
Application & sgl::Application::setTitle (const std::string & title)
Set the Title of the SFML window.
Parameters
title
Returns
Application&
Definition at line 39 of file Application.cpp.
References m_screen.
setVSync()
Application & sgl::Application::setVSync (bool state)
Set the Virtual Synchronization ON or OFF.
Settings the Virtual Synchronization ON will limit the FPS to 60
Parameters
state
Returns
Application&
Definition at line 45 of file Application.cpp.
References m_screen, and m_vsync.
Member Data Documentation
m_clock
sf::Clock sgl::Application::m_clock private
Definition at line 201 of file Application.hpp.
Referenced by run().
m_keys
Settings::Keys sgl::Application::m_keys private
Definition at line 198 of file Application.hpp.
m_profiler
internal::Profiler sgl::Application::m_profiler private
Definition at line 211 of file Application.hpp.
Referenced by run().
m_sceneManager
SceneManager sgl::Application::m_sceneManager private
Definition at line 202 of file Application.hpp.
Referenced by add(), run(), setCurrentScene(), and setCurrentSceneId().
m_screen
sf::RenderWindow sgl::Application::m_screen private
Definition at line 199 of file Application.hpp.
Referenced by Application(), run(), setFPSLimit(), setTitle(), and setVSync().
m_scriptingConfig
Scripting::Config sgl::Application::m_scriptingConfig private
Definition at line 206 of file Application.hpp.
Referenced by configureScriptingEngine(), and run().
m_scriptingEnabled
bool sgl::Application::m_scriptingEnabled private
Definition at line 205 of file Application.hpp.
Referenced by run(), and setScripting().
m_showDebug
bool sgl::Application::m_showDebug private
Definition at line 212 of file Application.hpp.
Referenced by setDebug().
m_state
Ark::State sgl::Application::m_state private
Definition at line 207 of file Application.hpp.
Referenced by configureScriptingEngine().
m_transformBase
sf::Transform sgl::Application::m_transformBase private
Definition at line 200 of file Application.hpp.
m_vm
Ark::VM sgl::Application::m_vm private
Definition at line 208 of file Application.hpp.
Referenced by configureScriptingEngine(), and run().
m_vsync
bool sgl::Application::m_vsync = false private
Definition at line 214 of file Application.hpp.
Referenced by setVSync().
m_wireframe
bool sgl::Application::m_wireframe = false private
Definition at line 213 of file Application.hpp.
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/include/Small/Core/Application.hpp
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/source/Core/Application.cpp