SmallGameLibrary: sgl::Scripting Namespace Reference
sgl::Scripting Namespace Reference
Easing the developer work to deploy a scripting API in the scenes and application.
Classes
struct Config
Host the scripting engine configuration.
Enumerations
enum class sfEventType {
TextEntered = 0 , KeyPressed , KeyReleased , MouseWheelScrolled ,
MouseButtonPressed , MouseButtonReleased
}
Enumeration of SFML event types, needed when binding events in ArkScript.
Functions
void bindCore (Ark::State *state, Application *app)
Bind the Core module of the library to ArkScript.
void bindGraphics (Ark::State *state)
Bind the Graphics module of the library to ArkScript.
void bindScenes (Ark::State *state)
Bind the Scenes module of the library to ArkScript.
void bindSystem (Ark::State *state)
Bind the System module of the library to ArkScript.
void bindWidgets (Ark::State *state)
Bind the Widgets module of the library to ArkScript.
bool compileScript (const std::string &file, const std::string &output, const std::string &arkscriptLibDir)
Compile an ArkScript file to ArkScript bytecode.
int compileAllScriptsIn (const std::string &path, const std::string &outputDir, const std::string &arkscriptLibDir)
Compile all scripts in a given directory, and put their output in another directory.
Ark::Value sfEventToArk (const sf::Event &event)
Convert a sf::Event to an ArkScript value.
Ark::Value sfTimeToArk (const sf::Time dt)
Convert a sf::time to an ArkScript value.
Ark::Value sglCoreAppSetTitle (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglCoreAppSetVSync (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglCoreAppSetFPSLimit (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglCoreAppSetDebug (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglCoreAppSetCurrentScene (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglGraphics (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglScenes (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglSystem (std::vector< Ark::Value > &args, Ark::VM *vm)
Ark::Value sglWidgets (std::vector< Ark::Value > &args, Ark::VM *vm)
Detailed Description
Easing the developer work to deploy a scripting API in the scenes and application.
Enumeration Type Documentation
sfEventType
enum class sgl::Scripting::sfEventType strong
Enumeration of SFML event types, needed when binding events in ArkScript.
Enumerator
TextEntered
KeyPressed
KeyReleased
MouseWheelScrolled
MouseButtonPressed
MouseButtonReleased
Definition at line 26 of file SFMLtoArk.hpp.
Function Documentation
bindCore()
void sgl::Scripting::bindCore (Ark::State * state, Application * app)
Bind the Core module of the library to ArkScript.
Parameters
state Pointer to a valid ArkScript state
app Pointer to the running application
Definition at line 89 of file Bindings.cpp.
References sglCoreAppSetCurrentScene(), sglCoreAppSetDebug(), sglCoreAppSetFPSLimit(), sglCoreAppSetTitle(), and sglCoreAppSetVSync().
Referenced by sgl::Application::configureScriptingEngine().
bindGraphics()
void sgl::Scripting::bindGraphics (Ark::State * state)
Bind the Graphics module of the library to ArkScript.
Parameters
state Pointer to a valid ArkScript state
Definition at line 111 of file Bindings.cpp.
References sglGraphics().
Referenced by sgl::Application::configureScriptingEngine(), and sgl::Scenes::ArkScene::init().
bindScenes()
void sgl::Scripting::bindScenes (Ark::State * state)
Bind the Scenes module of the library to ArkScript.
Parameters
state Pointer to a valid ArkScript state
Definition at line 131 of file Bindings.cpp.
References sglScenes().
Referenced by sgl::Application::configureScriptingEngine(), and sgl::Scenes::ArkScene::init().
bindSystem()
void sgl::Scripting::bindSystem (Ark::State * state)
Bind the System module of the library to ArkScript.
Parameters
state Pointer to a valid ArkScript state
Definition at line 149 of file Bindings.cpp.
References sglSystem().
Referenced by sgl::Application::configureScriptingEngine(), and sgl::Scenes::ArkScene::init().
bindWidgets()
void sgl::Scripting::bindWidgets (Ark::State * state)
Bind the Widgets module of the library to ArkScript.
Parameters
state Pointer to a valid ArkScript state
Definition at line 167 of file Bindings.cpp.
References sglWidgets().
Referenced by sgl::Application::configureScriptingEngine(), and sgl::Scenes::ArkScene::init().
compileAllScriptsIn()
int sgl::Scripting::compileAllScriptsIn (const std::string & path, const std::string & outputDir, const std::string & arkscriptLibDir)
Compile all scripts in a given directory, and put their output in another directory.
Parameters
path Path where the scripts lie
outputDir Path to put the compiled scripts
arkscriptLibDir Path to the ArkScript standard library
Returns
int Number of scripts successfully compiled
Definition at line 40 of file Engine.cpp.
References compileScript(), and sgl::System::listDir().
Referenced by sgl::Application::configureScriptingEngine().
compileScript()
bool sgl::Scripting::compileScript (const std::string & file, const std::string & output, const std::string & arkscriptLibDir)
Compile an ArkScript file to ArkScript bytecode.
Parameters
file Path to the ArkScript file to compile
output Output path where the bytecode should be saved (same filename, the extension becomes .arkc instead of .ark)
arkscriptLibDir Path to the ArkScript standard library
Returns
true If the file was successfuly compiled
false Otherwise
Definition at line 9 of file Engine.cpp.
Referenced by compileAllScriptsIn().
sfEventToArk()
Ark::Value sgl::Scripting::sfEventToArk (const sf::Event & event)
Convert a sf::Event to an ArkScript value.
Parameters
event
Returns
Ark::Value
Definition at line 5 of file SFMLtoArk.cpp.
References KeyPressed, KeyReleased, MouseButtonPressed, MouseButtonReleased, MouseWheelScrolled, and TextEntered.
Referenced by sgl::Scenes::ArkScene::onEvent().
sfTimeToArk()
Ark::Value sgl::Scripting::sfTimeToArk (const sf::Time dt)
Convert a sf::time to an ArkScript value.
Return the time as seconds
Parameters
dt
Returns
Ark::Value
Definition at line 55 of file SFMLtoArk.cpp.
Referenced by sgl::Scenes::ArkScene::onUpdate().
sglCoreAppSetCurrentScene()
Ark::Value sgl::Scripting::sglCoreAppSetCurrentScene (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 78 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindCore().
sglCoreAppSetDebug()
Ark::Value sgl::Scripting::sglCoreAppSetDebug (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 67 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_BOOL, and RETRIEVE_SGL_APP.
Referenced by bindCore().
sglCoreAppSetFPSLimit()
Ark::Value sgl::Scripting::sglCoreAppSetFPSLimit (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 56 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindCore().
sglCoreAppSetTitle()
Ark::Value sgl::Scripting::sglCoreAppSetTitle (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 34 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindCore().
sglCoreAppSetVSync()
Ark::Value sgl::Scripting::sglCoreAppSetVSync (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 45 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_BOOL, and RETRIEVE_SGL_APP.
Referenced by bindCore().
sglGraphics()
Ark::Value sgl::Scripting::sglGraphics (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 102 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindGraphics().
sglScenes()
Ark::Value sgl::Scripting::sglScenes (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 122 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindScenes().
sglSystem()
Ark::Value sgl::Scripting::sglSystem (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 140 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindSystem().
sglWidgets()
Ark::Value sgl::Scripting::sglWidgets (std::vector< Ark::Value > & args, Ark::VM * vm)
Definition at line 158 of file Bindings.cpp.
References ARK_AWAIT, ARK_CHECK_ARG, and RETRIEVE_SGL_APP.
Referenced by bindWidgets().