SmallGameLibrary: sgl::Widgets::Base Class Reference
sgl::Widgets::Base Class Reference
Base class for all widgets.
#include <Base.hpp>
Public Types
using Ptr = Base *
Public Member Functions
Base (int id, Ptr parent, const sf::IntRect &bounds)
Construct a new Base widget object.
virtual ~Base ()
Destroy the Base widget object.
virtual void onUpdate (const sf::Time dt)
Update the widget.
virtual void onRender (sf::RenderTarget &screen, const sf::Transform &transform)
Render the widget on screen.
virtual void onEvent (const sf::Event &event)
Called when an event is received, calling the subfunctions corresponding to the event type.
virtual void onTextEntered (sf::Uint32 code)
Called when a text entered event is produced, on focus.
virtual void onKeyPressed (int key)
Called when a key is pressed, on focus.
virtual void onKeyReleased (int key)
Called when a key is released, on focus.
virtual void onMouseWheelScrolled (float delta)
Called when the mouse wheel is scrolled, on focus.
virtual void onMouseButtonPressed (int button, int x, int y)
Called when a mouse button is pressed, on focus.
virtual void onMouseButtonReleased (int button, int x, int y)
Called when a mouse button is released, on focus.
virtual sf::FloatRect getLocalBounds () final
Get the local bounding rectangle of the entity.
virtual sf::FloatRect getGlobalBounds () final
Get the global bounding rectangle of the entity.
virtual void setListenToEvents (bool value) final
Activate a widget event listener or not.
virtual bool isListeningToEvents () const final
Return a boolean telling if the widget is listening to events.
virtual bool hasFocus () const final
Tell if the widget is being focused or not.
virtual void setStyle (Style style) final
Set the style of the object.
virtual Style getStyle () const final
Get the style of the widget.
template<typename T >
T * as ()
Return the widget as another type (should be a widget subclass)
Public Member Functions inherited from sgl::Graphics::Node
Node ()
Construct a new Node object.
virtual ~Node ()
Destroy the Node object.
Node & move (float x, float y)
Combine the current transform with a translation.
Node & move (const sf::Vector2f &offset)
Combine the current transform with a translation.
Node & rotate (float angle)
Combine the current transform with a rotation.
Node & rotate (float angle, float centerX, float centerY)
Combine the current transform with a rotation.
Node & rotate (float angle, const sf::Vector2f &center)
Combine the current transform with a rotation.
Node & scale (float scaleX, float scaleY)
Combine the current transform with a scaling.
Node & scale (const sf::Vector2f &factors)
Combine the current transform with a scaling.
Node & scale (float scaleX, float scaleY, float centerX, float centerY)
Combine the current transform with a scaling.
Node & scale (const sf::Vector2f &factors, const sf::Vector2f &center)
Combine the current transform with a scaling.
sf::Transform & getTransform ()
Get the Transform object.
template<typename N , typename... Args>
N * attach (Args &&... args)
Attach a child node to this node.
virtual void render (sf::RenderTarget &target, const sf::Transform &parent) final
Render a node using the parent transform, then its children.
Protected Attributes
const int m_id
Unique identifier for the widget.
bool m_focused
Tell if the widget is being focused or not.
bool m_listening
Tell if a widget can receive events.
sf::IntRect m_rect
Rectangle in which the widget is.
Ptr m_parent
Pointer to the parent widget.
Style m_style
Protected Attributes inherited from sgl::Graphics::Node
std::vector< std::shared_ptr< Node > > m_children
Detailed Description
Base class for all widgets.
This class can not be used as is.
Providing base features like: focus management, update on event, rendering, transformations. Position is always relative to the parent.
Definition at line 40 of file Base.hpp.
Member Typedef Documentation
Ptr
using sgl::Widgets::Base::Ptr = Base*
Definition at line 43 of file Base.hpp.
Constructor & Destructor Documentation
Base()
sgl::Widgets::Base::Base (int id, Base::Ptr parent, const sf::IntRect & bounds)
Construct a new Base widget object.
Parameters
id Unique identifier for the widget (automatically set)
parent Pointer to the parent widget (automatically set)
bounds Local bounds of the widget
Definition at line 5 of file Base.cpp.
References sgl::Graphics::Node::move(), and sgl::Widgets::Text.
~Base()
sgl::Widgets::Base::~Base () virtual
Destroy the Base widget object.
Definition at line 12 of file Base.cpp.
Member Function Documentation
as()
template<typename T > T * sgl::Widgets::Base::as () inline
Return the widget as another type (should be a widget subclass)
Template Parameters
T The widget type
Returns
T* A pointer to the widget (use at your own risks, if it's not a widget subclass, it will result in an undefined behaviour)
Definition at line 191 of file Base.hpp.
getGlobalBounds()
sf::FloatRect sgl::Widgets::Base::getGlobalBounds () final virtual
Get the global bounding rectangle of the entity.
The returned rectangle is in global coordinates, taking into account transformations.
Returns
sf::FloatRect
Definition at line 95 of file Base.cpp.
References getGlobalBounds(), getLocalBounds(), sgl::Graphics::Node::getTransform(), and m_parent.
Referenced by getGlobalBounds(), and onEvent().
getLocalBounds()
sf::FloatRect sgl::Widgets::Base::getLocalBounds () final virtual
Get the local bounding rectangle of the entity.
The returned rectangle is in local coordinates, ignoring transformations.
Returns
sf::FloatRect
Definition at line 88 of file Base.cpp.
References m_rect.
Referenced by getGlobalBounds().
getStyle()
Style sgl::Widgets::Base::getStyle () const final virtual
Get the style of the widget.
Returns
Style
Definition at line 126 of file Base.cpp.
References m_style.
Referenced by sgl::Widgets::Button::onRender().
hasFocus()
bool sgl::Widgets::Base::hasFocus () const final virtual
Tell if the widget is being focused or not.
Returns
true If the widget has the focus
false Otherwise
Definition at line 116 of file Base.cpp.
References m_focused.
Referenced by sgl::Widgets::Layout::onEvent().
isListeningToEvents()
bool sgl::Widgets::Base::isListeningToEvents () const final virtual
Return a boolean telling if the widget is listening to events.
Returns
true If the widget can receive events
false Otherwise
Definition at line 111 of file Base.cpp.
References m_listening.
Referenced by sgl::Widgets::Layout::onEvent().
onEvent()
void sgl::Widgets::Base::onEvent (const sf::Event & event) virtual
Called when an event is received, calling the subfunctions corresponding to the event type.
Parameters
event
Reimplemented in sgl::Widgets::Layout.
Definition at line 21 of file Base.cpp.
References getGlobalBounds(), m_focused, onKeyPressed(), onKeyReleased(), onMouseButtonPressed(), onMouseButtonReleased(), onMouseWheelScrolled(), and onTextEntered().
Referenced by sgl::Widgets::Layout::onEvent().
onKeyPressed()
void sgl::Widgets::Base::onKeyPressed (int key) virtual
Called when a key is pressed, on focus.
Parameters
key the key code of the key pressed
Definition at line 73 of file Base.cpp.
Referenced by onEvent().
onKeyReleased()
void sgl::Widgets::Base::onKeyReleased (int key) virtual
Called when a key is released, on focus.
Parameters
key the key code of the key released
Definition at line 76 of file Base.cpp.
Referenced by onEvent().
onMouseButtonPressed()
void sgl::Widgets::Base::onMouseButtonPressed (int button, int x, int y) virtual
Called when a mouse button is pressed, on focus.
Focus is handled before calling the method
Parameters
button the button pressed (sf::Mouse::Button)
x position of the click
y position of the click
Reimplemented in sgl::Widgets::Button.
Definition at line 82 of file Base.cpp.
Referenced by onEvent().
onMouseButtonReleased()
void sgl::Widgets::Base::onMouseButtonReleased (int button, int x, int y) virtual
Called when a mouse button is released, on focus.
Focus is handled before calling the method
Parameters
button the button released (sf::Mouse::Button)
x position of the click
y position of the click
Reimplemented in sgl::Widgets::Button.
Definition at line 85 of file Base.cpp.
Referenced by onEvent().
onMouseWheelScrolled()
void sgl::Widgets::Base::onMouseWheelScrolled (float delta) virtual
Called when the mouse wheel is scrolled, on focus.
Parameters
delta Delta of movement of the wheel (positive is up/left, negative is down/right)
Definition at line 79 of file Base.cpp.
Referenced by onEvent().
onRender()
void sgl::Widgets::Base::onRender (sf::RenderTarget & screen, const sf::Transform & transform) virtual
Render the widget on screen.
Parameters
screen
transform Given by parent automatically
Implements sgl::Graphics::Node.
Reimplemented in sgl::Widgets::Button, sgl::Widgets::Image, sgl::Widgets::Label, and sgl::Widgets::Layout.
Definition at line 18 of file Base.cpp.
onTextEntered()
void sgl::Widgets::Base::onTextEntered (sf::Uint32 code) virtual
Called when a text entered event is produced, on focus.
Parameters
code character unicode
Definition at line 70 of file Base.cpp.
Referenced by onEvent().
onUpdate()
void sgl::Widgets::Base::onUpdate (const sf::Time dt) virtual
Update the widget.
Parameters
dt Delta of time since last update
Reimplemented in sgl::Widgets::Layout.
Definition at line 15 of file Base.cpp.
setListenToEvents()
void sgl::Widgets::Base::setListenToEvents (bool value) final virtual
Activate a widget event listener or not.
Parameters
value
Definition at line 106 of file Base.cpp.
References m_listening.
Referenced by sgl::Widgets::Label::Label().
setStyle()
void sgl::Widgets::Base::setStyle (Style style) final virtual
Set the style of the object.
Parameters
style a Style enumeration value
Definition at line 121 of file Base.cpp.
References m_style.
Member Data Documentation
m_focused
bool sgl::Widgets::Base::m_focused protected
Tell if the widget is being focused or not.
Definition at line 198 of file Base.hpp.
Referenced by hasFocus(), onEvent(), and sgl::Widgets::Layout::onEvent().
m_id
const int sgl::Widgets::Base::m_id protected
Unique identifier for the widget.
Definition at line 197 of file Base.hpp.
m_listening
bool sgl::Widgets::Base::m_listening protected
Tell if a widget can receive events.
Definition at line 199 of file Base.hpp.
Referenced by isListeningToEvents(), and setListenToEvents().
m_parent
Ptr sgl::Widgets::Base::m_parent protected
Pointer to the parent widget.
Definition at line 201 of file Base.hpp.
Referenced by getGlobalBounds().
m_rect
sf::IntRect sgl::Widgets::Base::m_rect protected
Rectangle in which the widget is.
Definition at line 200 of file Base.hpp.
Referenced by getLocalBounds().
m_style
Style sgl::Widgets::Base::m_style protected
Definition at line 202 of file Base.hpp.
Referenced by getStyle(), and setStyle().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/include/Small/Widgets/Base.hpp
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/source/Widgets/Base.cpp