SmallGameLibrary: sgl::Graphics::AnimatedSprite Class Reference
sgl::Graphics::AnimatedSprite Class Reference
Animated sprite based on the animation class.
#include <Animation.hpp>
Public Member Functions
AnimatedSprite (bool paused=false, bool looped=true)
Construct a new Animated Sprite object.
void update (sf::Time deltaTime)
Update the sprite.
void setAnimation (const Animation &animation)
Set the Animation object.
void play ()
Play animation.
void play (const Animation &animation)
Play given animation.
void pause ()
Pause animation.
void stop ()
Stop animation.
void setLooped (bool looped)
Set looped.
void setColor (const sf::Color &color)
Set the Color object.
const Animation * getAnimation () const
Get the Animation object.
sf::FloatRect getLocalBounds () const
Get the Local Bounds object.
sf::FloatRect getGlobalBounds () const
Get the Global Bounds object.
bool isLooped () const
Is the animation looping?
bool isPlaying () const
Is the animation playing?
void setFrame (std::size_t newFrame, bool resetTime=true)
Set the Frame object.
bool isEnd () const
Check if the end frame has been reached.
Private Member Functions
virtual void draw (sf::RenderTarget &target, sf::RenderStates states) const
Draw the sprite using SFML API.
Private Attributes
const Animation * m_animation
sf::Time m_currentTime
std::size_t m_currentFrame
bool m_isPaused
bool m_isLooped
const sf::Texture * m_texture
sf::Vertex m_vertices [4]
Detailed Description
Animated sprite based on the animation class.
Definition at line 132 of file Animation.hpp.
Constructor & Destructor Documentation
AnimatedSprite()
sgl::Graphics::AnimatedSprite::AnimatedSprite (bool paused = false, bool looped = true)
Construct a new Animated Sprite object.
Parameters
paused Is the animation paused?
looped Is the animation looping?
Definition at line 71 of file Animation.cpp.
Member Function Documentation
draw()
void sgl::Graphics::AnimatedSprite::draw (sf::RenderTarget & target, sf::RenderStates states) const private virtual
Draw the sprite using SFML API.
Parameters
target
states
Definition at line 225 of file Animation.cpp.
References m_animation, m_texture, and m_vertices.
getAnimation()
const Animation * sgl::Graphics::AnimatedSprite::getAnimation () const
Get the Animation object.
Returns
const Animation*
Definition at line 122 of file Animation.cpp.
References m_animation.
Referenced by play().
getGlobalBounds()
sf::FloatRect sgl::Graphics::AnimatedSprite::getGlobalBounds () const
Get the Global Bounds object.
Returns
sf::FloatRect
Definition at line 137 of file Animation.cpp.
References getLocalBounds().
getLocalBounds()
sf::FloatRect sgl::Graphics::AnimatedSprite::getLocalBounds () const
Get the Local Bounds object.
Returns
sf::FloatRect
Definition at line 127 of file Animation.cpp.
References m_currentFrame.
Referenced by getGlobalBounds().
isEnd()
bool sgl::Graphics::AnimatedSprite::isEnd () const
Check if the end frame has been reached.
Returns
true
false
Definition at line 220 of file Animation.cpp.
References sgl::Graphics::Animation::getEnd(), m_animation, and m_currentFrame.
Referenced by update().
isLooped()
bool sgl::Graphics::AnimatedSprite::isLooped () const
Is the animation looping?
Returns
true
false
Definition at line 142 of file Animation.cpp.
References m_isLooped.
isPlaying()
bool sgl::Graphics::AnimatedSprite::isPlaying () const
Is the animation playing?
Returns
true
false
Definition at line 147 of file Animation.cpp.
References m_isPaused.
pause()
void sgl::Graphics::AnimatedSprite::pause ()
Pause animation.
Definition at line 96 of file Animation.cpp.
References m_isPaused.
play() [1/2]
void sgl::Graphics::AnimatedSprite::play ()
Play animation.
Definition at line 84 of file Animation.cpp.
References m_isPaused.
Referenced by play().
play() [2/2]
void sgl::Graphics::AnimatedSprite::play (const Animation & animation)
Play given animation.
Parameters
animation
Definition at line 89 of file Animation.cpp.
References getAnimation(), play(), and setAnimation().
setAnimation()
void sgl::Graphics::AnimatedSprite::setAnimation (const Animation & animation)
Set the Animation object.
Parameters
animation
Definition at line 76 of file Animation.cpp.
References sgl::Graphics::Animation::getSpriteSheet(), m_animation, m_currentFrame, m_texture, and setFrame().
Referenced by play().
setColor()
void sgl::Graphics::AnimatedSprite::setColor (const sf::Color & color)
Set the Color object.
Parameters
color
Definition at line 113 of file Animation.cpp.
References m_vertices.
setFrame()
void sgl::Graphics::AnimatedSprite::setFrame (std::size_t newFrame, bool resetTime = true)
Set the Frame object.
Parameters
newFrame
resetTime
Definition at line 152 of file Animation.cpp.
References sgl::Graphics::Animation::isXInverted(), m_animation, m_currentTime, and m_vertices.
Referenced by setAnimation(), stop(), and update().
setLooped()
void sgl::Graphics::AnimatedSprite::setLooped (bool looped)
Set looped.
Parameters
looped
Definition at line 108 of file Animation.cpp.
References m_isLooped.
stop()
void sgl::Graphics::AnimatedSprite::stop ()
Stop animation.
Definition at line 101 of file Animation.cpp.
References m_currentFrame, m_isPaused, and setFrame().
update()
void sgl::Graphics::AnimatedSprite::update (sf::Time deltaTime)
Update the sprite.
Parameters
deltaTime Delta of time since last update
Definition at line 188 of file Animation.cpp.
References sgl::Graphics::Animation::getFrameTime(), isEnd(), m_animation, m_currentFrame, m_currentTime, m_isLooped, m_isPaused, setFrame(), and sgl::Graphics::Animation::size().
Member Data Documentation
m_animation
const Animation* sgl::Graphics::AnimatedSprite::m_animation private
Definition at line 250 of file Animation.hpp.
Referenced by draw(), getAnimation(), isEnd(), setAnimation(), setFrame(), and update().
m_currentFrame
std::size_t sgl::Graphics::AnimatedSprite::m_currentFrame private
Definition at line 252 of file Animation.hpp.
Referenced by getLocalBounds(), isEnd(), setAnimation(), stop(), and update().
m_currentTime
sf::Time sgl::Graphics::AnimatedSprite::m_currentTime private
Definition at line 251 of file Animation.hpp.
Referenced by setFrame(), and update().
m_isLooped
bool sgl::Graphics::AnimatedSprite::m_isLooped private
Definition at line 254 of file Animation.hpp.
Referenced by isLooped(), setLooped(), and update().
m_isPaused
bool sgl::Graphics::AnimatedSprite::m_isPaused private
Definition at line 253 of file Animation.hpp.
Referenced by isPlaying(), pause(), play(), stop(), and update().
m_texture
const sf::Texture* sgl::Graphics::AnimatedSprite::m_texture private
Definition at line 255 of file Animation.hpp.
Referenced by draw(), and setAnimation().
m_vertices
sf::Vertex sgl::Graphics::AnimatedSprite::m_vertices[4] private
Definition at line 256 of file Animation.hpp.
Referenced by draw(), setColor(), and setFrame().
The documentation for this class was generated from the following files:
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/include/Small/Graphics/Animation.hpp
C:/Users/folae/Documents/Code/Big-Projects/ScriptWizards/SmallGameLibrary/source/Graphics/Animation.cpp